import { JobFormData } from "@/types/job";

/** 10 demo job applications covering all statuses, sources, and currencies. */
export const DEMO_JOBS: JobFormData[] = [
  {
    companyName: "Stripe",
    jobTitle: "Senior Frontend Engineer",
    jobLink: "",
    salaryExpected: 90000,
    salaryProposed: 95000,
    salaryCurrency: "EUR",
    source: "linkedin",
    timeline: [
      { status: "submitted", date: "2026-02-01" },
      { status: "first_call", date: "2026-02-08", note: "30 min with recruiter" },
      { status: "technical_interview", date: "2026-02-15", note: "Live coding — React" },
    ],
  },
  {
    companyName: "Airbnb",
    jobTitle: "React Developer",
    jobLink: "",
    salaryExpected: 100000,
    salaryProposed: 110000,
    salaryCurrency: "USD",
    source: "linkedin",
    timeline: [
      { status: "submitted", date: "2026-02-05" },
      { status: "first_call", date: "2026-02-12" },
      { status: "second_interview", date: "2026-02-20", note: "Panel with eng team" },
      { status: "offer_received", date: "2026-03-01" },
    ],
  },
  {
    companyName: "Spotify",
    jobTitle: "Frontend Engineer",
    jobLink: "",
    salaryExpected: 80000,
    salaryProposed: 85000,
    salaryCurrency: "EUR",
    source: "company_website",
    timeline: [
      { status: "submitted", date: "2026-02-10" },
      { status: "first_call", date: "2026-02-18", note: "Culture fit call" },
    ],
  },
  {
    companyName: "Netflix",
    jobTitle: "UI Engineer",
    jobLink: "",
    salaryExpected: 120000,
    salaryProposed: 130000,
    salaryCurrency: "USD",
    source: "referral",
    notes: "Referred by ex-colleague Maria. Focus on performance.",
    timeline: [
      { status: "submitted", date: "2026-02-14" },
      { status: "first_call", date: "2026-02-21" },
      { status: "technical_interview", date: "2026-03-01", note: "System design + React" },
      { status: "second_interview", date: "2026-03-10" },
      { status: "approved", date: "2026-03-20" },
    ],
  },
  {
    companyName: "Shopify",
    jobTitle: "Full Stack Developer",
    jobLink: "",
    salaryExpected: 72000,
    salaryProposed: 75000,
    salaryCurrency: "GBP",
    source: "job_board",
    timeline: [
      { status: "submitted", date: "2026-02-20" },
      { status: "rejected", date: "2026-03-05", note: "Not enough backend experience" },
    ],
  },
  {
    companyName: "Notion",
    jobTitle: "Product Engineer",
    jobLink: "",
    salaryExpected: 90000,
    salaryProposed: null,
    salaryCurrency: "USD",
    source: "linkedin",
    notes: "Great product, very interested. No response after application.",
    timeline: [
      { status: "submitted", date: "2026-02-25" },
      { status: "never_answered", date: "2026-03-18" },
    ],
  },
  {
    companyName: "Linear",
    jobTitle: "Software Engineer",
    jobLink: "",
    salaryExpected: 85000,
    salaryProposed: 88000,
    salaryCurrency: "EUR",
    source: "referral",
    timeline: [
      { status: "submitted", date: "2026-03-01" },
      { status: "first_call", date: "2026-03-08", note: "With CTO" },
      { status: "technical_interview", date: "2026-03-15" },
    ],
  },
  {
    companyName: "Vercel",
    jobTitle: "Frontend Developer",
    jobLink: "",
    salaryExpected: 95000,
    salaryProposed: null,
    salaryCurrency: "USD",
    source: "company_website",
    notes: "Applied via website. Remote-first team.",
    timeline: [
      { status: "submitted", date: "2026-03-05" },
    ],
  },
  {
    companyName: "GitHub",
    jobTitle: "Senior Software Engineer",
    jobLink: "",
    salaryExpected: 115000,
    salaryProposed: 120000,
    salaryCurrency: "USD",
    source: "linkedin",
    timeline: [
      { status: "submitted", date: "2026-03-10" },
      { status: "first_call", date: "2026-03-17", note: "Intro call — went well" },
    ],
  },
  {
    companyName: "Figma",
    jobTitle: "Web Developer",
    jobLink: "",
    salaryExpected: 75000,
    salaryProposed: 78000,
    salaryCurrency: "EUR",
    source: "job_board",
    timeline: [
      { status: "submitted", date: "2026-03-15" },
      { status: "first_call", date: "2026-03-22" },
      { status: "rejected", date: "2026-04-02", note: "Went with internal candidate" },
    ],
  },
];
